ui_print "__________________Applied Patches_______________"
ui_print " "
ui_print "            *Louder Dual Speaker"
ui_print " "
ui_print "            *Sound Quality Improved"
ui_print " "
ui_print "            *Low Call Volume Fixed"
ui_print " "
ui_print "            *UI Response Improved"
ui_print " "
ui_print "            *Touch Response Improved"
ui_print " "
ui_print "            *Memory Management Improved"
ui_print " "
ui_print "            *OTG Issue Fixed"
ui_print " "
ui_print "            *Raw Enabled"
ui_print " "
ui_print "            *50mp Fixed"
ui_print " "
ui_print "            *5k battery overlay enabled"
ui_print " "
ui_print "            *Cam Lag Fixed (bufferfix)"
ui_print " "
ui_print "            *AuxCameras Enabled"
ui_print " "
ui_print "            *Screen Recorder Fixed"
ui_print " "
ui_print "            *Subscribe @SourovKhanNahid on YT"
ui_print " "
ui_print "            *Then Reboot Your Device"
ui_print " "
